### ISSUE TITLE
Missing modules in release

### ISSUE THREAD

**Issue by bergmark** [ryantm/heyefi#2]
heyefi's cabal file doesn't list any modules so source files are not included in the release tarball. Everything except Main needs to be added to `other-modules` of the executable or under a `library` section.. You can test this before releasing by doing `cabal sdist && cabal install dist/heyefi-version.tar.gz`

Build logs: http://matrix.hackage.haskell.org/package/heyefi#GHC-7.10/heyefi-0.1.0.0

**Comment by ryantm** [comment]
Hi, @bergmark.

I noticed that build log problem but hadn't figured it out yet. Your explanation is very helpful! I will probably fix it tomorrow morning.

Ryan

**Comment by ryantm** [comment]
Fixed, thanks.
